[opentelemetry]
opentelemetry.enabled = On
opentelemetry.service_name = "php-fpm"
opentelemetry.traces_exporter = otlp_http
opentelemetry.metrics_exporter = otlp_http
opentelemetry.logs_exporter = otlp_http
opentelemetry.psr15_auto_instrumentation_enabled = On

; Environment variables are injected via docker-compose
; OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
; OTEL_SERVICE_NAME=php-fpm