[opentelemetry]
opentelemetry.enabled = On
opentelemetry.service_name = "php-fpm"
opentelemetry.traces_exporter = otlp
opentelemetry.metrics_exporter = otlp
opentelemetry.logs_exporter = otlp
opentelemetry.psr15_auto_instrumentation_enabled = On

; Environment variables are injected via docker-compose
; OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
; OTEL_SERVICE_NAME=php-fpm