name: Pull Request Build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  php_version:
    runs-on: ubuntu-latest
    outputs:
      php_version: ${{ steps.vars.outputs.php_version }}
    steps:
      - name: Set shared build variables
        id: vars
        run: echo "php_version=8.4" >> "$GITHUB_OUTPUT"

  php-fpm:
    needs: php_version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/.docker-build-sign.yml
    with:
      context: .
      file: ./php/fpm/Dockerfile
      image_name: matriphe/docker/php
      image_tag: PR-${{ github.event.pull_request.number || github.run_number }}
      build_args: |
        PHP_VERSION=${{ needs.php_version.outputs.php_version }}
      push_image: true
      sign_image: false
    secrets: inherit

  wordpress:
    needs: php_version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/.docker-build-sign.yml
    with:
      context: .
      file: ./wordpress/Dockerfile
      image_name: matriphe/docker/wordpress
      image_tag: PR-${{ github.event.pull_request.number || github.run_number }}
      build_args: |
        PHP_VERSION=${{ needs.php_version.outputs.php_version }}
      push_image: true
      sign_image: false
    secrets: inherit
